### PR TITLE
feat!: remove test only for Datasamples

### PR DESCRIPTION
**Pull request by ThibaultFy**
## Companion PR

- https://github.com/Substra/substra/pull/332 - MAIN
- https://github.com/Substra/substra-backend/pull/551
- https://github.com/Substra/substra-documentation/pull/246
- https://github.com/Substra/substrafl/pull/67
- https://github.com/Substra/substra-tests/pull/235
- https://github.com/Substra/orchestrator/pull/116

## Asana

https://app.asana.com/0/1202209633046022/1203074394111393/f

### CODE REVIEW

**Comment by Owlfred** [comment]
```
Usage: /e2e [options] [help]

/e2e may appear anywhere as long as it is on its own line

Options:
  --refs <value>                                         Extra refs (branch or tag) with format REPO=GIT_REF,REPO=GIT_REF.
  Supported repositories: substra-hlf-k8s, orchestrator, substra-backend, substra-frontend, substra-tools, substrafl, substra, substra-tests, substra-ci.
  Example: /e2e --refs substra-backend=some_branch,orchestrator=some_tag (default: {})
  --tests-to-run, --tests <tests-to-run>                 Comma-separated list of tests to run. Valid options: sdk,substrafl,frontend or NONE. (default: "sdk")
  --benchmarks-to-run, --benchmarks <benchmarks-to-run>  Comma-separated list of workflows tests to run. Valid options: mnist, camelyon or NONE. (default: "NONE")
  --orchestrator-mode, --mode <orchestrator-mode>        Comma-separated list of orchestrator modes to run tests for. Valid options: standalone,distributed (default: "standalone,distributed")
  -h, --help                                             display help for command
```

**Comment by ThibaultFy** [comment]
/e2e --refs substra=feat/rm-test-only,substrafl=feat/rm-test-only --tests=sdk,substrafl --mode=standalone --benchmarks=mnist,camelyon

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --refs substra=feat/rm-test-only,substrafl=feat/rm-test-only,substra-tests=feat/rm-test-only --tests=sdk,substrafl --mode=standalone

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --refs substra=feat/rm-test-only,substrafl=feat/rm-test-only,substra-tests=feat/rm-test-only --tests=sdk,substrafl --mode=standalone

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --refs orchestrator=feat/rm-test-only,substra-backend=feat/rm-test-only,substra=feat/rm-test-only,substrafl=feat/rm-test-only,substra-tests=feat/rm-test-only --tests=sdk,substrafl,frontend --mode=standalone,distributed --benchmark=mnist,camelyon

**Comment by ThibaultFy** [comment]
/e2e --refs orchestrator=feat/rm-test-only,substra-backend=feat/rm-test-only,substra=feat/rm-test-only,substrafl=feat/rm-test-only,substra-tests=feat/rm-test-only --tests=sdk,substrafl,frontend --mode=standalone,distributed --benchmarks=mnist,camelyon

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --refs orchestrator=feat/rm-test-only,substra-backend=feat/rm-test-only,substra=feat/rm-test-only,substrafl=feat/rm-test-only,substra-tests=feat/rm-test-only --tests=sdk,substrafl,frontend --mode=standalone,distributed --benchmarks=mnist,camelyon

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --refs orchestrator=feat/rm-test-only,substra-backend=feat/rm-test-only,substra=feat/rm-test-only,substrafl=feat/rm-test-only,substra-tests=feat/rm-test-only --tests=sdk,substrafl,frontend --mode=standalone,distributed --benchmarks=mnist,camelyon

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by guilhem-barthes — APPROVED** [review]
LGTM!

**Pull request merged**
